[versions]

# Gradle Plugins
shadow = "8.1.1"
pluginyml = "0.6.0"

# Utilities
annotation = "24.1.0"

# Paper
paper = "1.20.2-R0.1-SNAPSHOT"

[libraries]

annotation = { group = "org.jetbrains", name = "annotations", version.ref = "annotation" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }

[plugins]

shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
pluginyml = { id = "net.minecrell.plugin-yml.paper", version.ref = "pluginyml" }
